import io
from datetime import datetime

from flask import Blueprint, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from models import User
from services.skill_matcher import analyze_gap

bp = Blueprint("report", __name__, url_prefix="/api/report")

STATUS_COLORS = {
    "Strong": colors.HexColor("#1F9D7C"),
    "Developing": colors.HexColor("#B8860B"),
    "Missing": colors.HexColor("#C0392B"),
}


@bp.get("/gap-report.pdf")
@jwt_required()
def gap_report_pdf():
    """Renders the current user's gap analysis as a downloadable PDF —
    the thing the Settings page's "Download gap report" button calls."""
    user = User.query.get_or_404(int(get_jwt_identity()))
    if not user.target_role:
        return {"error": "Set a target_role first"}, 400

    result = analyze_gap(
        [s.skill_id for s in user.skills],
        user.target_role,
        user.experience_level or "Fresher",
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleBig", parent=styles["Title"], fontSize=22, spaceAfter=4)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=11, textColor=colors.grey)

    story = [
        Paragraph("SkillRadar — Gap Analysis Report", title_style),
        Paragraph(
            f"{user.name} &nbsp;&middot;&nbsp; Target role: {result['target_role']} "
            f"&nbsp;&middot;&nbsp; Experience: {result['experience_level']} "
            f"&nbsp;&middot;&nbsp; Generated {datetime.now().strftime('%d %b %Y')}",
            subtitle_style,
        ),
        Spacer(1, 6 * mm),
        Paragraph(f"<b>Readiness score: {result['readiness_score']}%</b>", styles["Heading2"]),
        Spacer(1, 4 * mm),
    ]

    table_data = [["Skill", "Category", "Required", "Your score", "Status"]]
    for b in result["breakdown"]:
        table_data.append([b["skill_name"], b["category"], str(b["required"]), str(b["user_score"]), b["status"]])

    table = Table(table_data, colWidths=[42 * mm, 32 * mm, 24 * mm, 28 * mm, 28 * mm])
    style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1B1F2E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F5EF")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDAD0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]
    for row_idx, b in enumerate(result["breakdown"], start=1):
        style_commands.append(("TEXTCOLOR", (4, row_idx), (4, row_idx), STATUS_COLORS.get(b["status"], colors.black)))
        style_commands.append(("FONTNAME", (4, row_idx), (4, row_idx), "Helvetica-Bold"))
    table.setStyle(TableStyle(style_commands))
    story.append(table)

    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Generated by SkillRadar. Readiness score reflects self-reported skills scaled by "
        "experience level against the role's requirement template — treat it as a guide, not "
        "a guarantee.", ParagraphStyle("Footnote", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(story)
    buffer.seek(0)

    filename = f"skillradar-gap-report-{user.name.replace(' ', '-').lower()}.pdf"
    return send_file(buffer, mimetype="application/pdf", as_attachment=True, download_name=filename)
